packages:
  - "backend"
  - "frontend/*"
  - "packages/*"

catalog:
  "nuxt": ~4.0.3
  "vue": ~3.5.20
  "vue-tsc": ~3.0.6
  "vue-router": ~4.5.1

  "zod": ~4.1.4

  "@trpc/server": ~11.5.0
  "@trpc/client": ~11.5.0

  "eslint": ~9.34.0
  "typescript": ~5.9.2
